version: "3"

services:
  web-server:
    build: .
    container_name: "aws-php-labs"
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
    environment:
      PHP_EXTENSION_PDO_SQLITE: 1
      PHP_INI_ERROR_REPORTING: 1
